server:
  port: 8080

spring:
  application:
    name: yunxiangxianlu
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/yunxiangxianlu?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
      username: root
      password: Crq123456&
      driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    maximum-pool-size: 10
    minimum-idle: 5
    idle-timeout: 60000
    connection-timeout: 30000
    max-lifetime: 1800000
    connection-test-query: select 1

mybatis-plus:
    mapper-locations: classpath*:mapper/*.xml
    type-aliases-package: org.yunxiangxianlu.dal.entity
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# JWT配置
jwt:
  secret: VqSNsMV9Oq1bRpb3emt6Cyxww0t0Xb7lzAmnStlalTCENnPd7tNJ4YD0xmIZIlIj
  expiration: 3600000  # 1小时，单位毫秒
  refresh-expiration: 86400000  # 24小时，单位毫秒

# 跨域配置
cors:
  allowed-origins: http://localhost:8080,http://127.0.0.1:8080
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true